# Generated by Django 6.0.5 on 2026-06-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_completed_task_priority_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
